### ISSUE TITLE
Unable to Start - bad options: env

### ISSUE THREAD

**Issue by jammyjkdev** [almeidx/discord-ban-sync#276]
Hi there, I am unable to start the bot due to .env errors however from what I believe ive entered everything correctly? 

<img width="1044" alt="image" src="https://github.com/almeidx/discord-ban-sync/assets/102424128/a367a3eb-32af-47bf-9ada-090a85b2011b">
<img width="752" alt="image" src="https://github.com/almeidx/discord-ban-sync/assets/102424128/26c40025-6d8e-4e23-a14d-863ef1188f76">

**Comment by almeidx** [comment]
Seems like you have an outdated node.js version, as seen in the warnings you got when running `pnpm` commands. The minimum required version is `v20.6.0`
